# Generated by Django 5.0 on 2024-12-28 17:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_name', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='response',
            name='completion_time',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='response',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
